//
//  EnableLocationServicesPresenter.swift
//  Ionix App
//
//  Created by Carlos Villamizar on 29/7/21.
//

import Foundation

protocol EnableLocationServicesPresentationLogic {
    func presentSomething(response: EnableLocationServices.Something.Response)
}

class EnableLocationServicesPresenter: EnableLocationServicesPresentationLogic {
    weak var viewController: EnableLocationServicesDisplayLogic?
  
    // MARK: - Do something
    /* Is the class which is responsible for presenting the object which
    is generated by the Interactor.*/
    func presentSomething(response: EnableLocationServices.Something.Response) {
        let viewModel = EnableLocationServices.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
